// In "@/lib/Index.ts"
export const projects = [
  {
    id: 1,
    title: "School Management System",
    description:
      "Modern and responsive School Management System.",
    liveUrl: "/",
    Image: "https://drive.google.com/uc?export=view&id=1aT60AeiW9NQQfA9ltTWW35HtAahsV7Pl",
    tags: ["React js","TypeScript", "Tailwind CSS","Node.js", "Express.js", "MySQL"],
    rating: 5,
  },
  {
    id: 2,
    title: "Car Rental System",
    description: "Clean and energetic and user-friendly Car Rental System.",
    liveUrl: "https://grabacar.xyz/",
    Image: "/projects/car.png",
    tags: ["Laravel", "CSS", "JavaScript", "MySQL"],
    rating: 5,
  },
  // {
  //   id: 3,
  //   title: "Jewelry Store UI",
  //   description:
  //     "Elegant and luxury-style frontend for an online jewelry store.",
  //   liveUrl: "https://jewelry-orpin.vercel.app",
  //   Image: "/projects/jewelry.jpeg",
  //   tags: ["React js"],
  //   rating: 5,
  // },
  // {
  //   id: 4,
  //   title: "Restaurant Website Design",
  //   description: "Minimalist and engaging layout for a modern restaurant.",
  //   liveUrl: "https://qitchendummy.vercel.app",
  //   Image: "/projects/restorent.jpeg",
  //   tags: ["React js"],
  //   rating: 5,
  // },
  // {
  //   id: 5,
  //   title: "Salon Booking UI",
  //   description:
  //     "Stylish and intuitive frontend for a salon appointment system.",
  //   liveUrl: "https://salondummy.vercel.app",
  //   Image: "/projects/salon.jpeg",
  //   tags: ["React js"],
  //   rating: 5,
  // },
  // {
  //   id: 6,
  //   title: "Dental Booking UI",
  //   description:
  //     "Stylish and intuitive frontend for a Dental appointment system.",
  //   liveUrl: "https://dainteldummy.vercel.app",
  //   Image: "/projects/dental.jpg",
  //   tags: ["React js"],
  //   rating: 5,
  // },
];
export const items = [
   {
    id: 1,
    title: "School Management System",
    description:
      "Modern and responsive School Management System.",
    liveUrl: "/",
    images: ["https://drive.google.com/uc?export=view&id=1aT60AeiW9NQQfA9ltTWW35HtAahsV7Pl"],
    tags: ["React js","TypeScript", "Tailwind CSS","Node.js", "Express.js", "MySQL"],
     year: "2024",
     client: "My project",
     services: "full stack development",
    project: "full stack",
     rating: 4,
  },
  {
    id: "2",
    title: "Car Rental System",
    description:
      "Clean and energetic and user-friendly Car Rental System.",
    images: ["/projects/car.png"],
    liveUrl: "https://grabacar.xyz",
    rating: 5,
    tags: ["Laravel", "CSS", "JavaScript", "MySQL"],
    year: "2025",
    client: "My project",
    services: "full stack development",
    project: "full stack",
  },
  // {
  //   id: "3",
  //   title: "Luxury Jewelry Storefront",
  //   description:
  //     "An elegant online storefront for a premium jewelry brand. Designed with minimalism and luxury in mind, focusing on product showcases and a seamless shopping experience.",
  //   images: ["/projects/jewelry.jpeg"],
  //   liveUrl: "https://jewelry-orpin.vercel.app",
  //   rating: 5,
  //   tags: ["Frontend", "eCommerce"],
  //   year: "2024",
  //   client: "Lustre & Co.",
  //   services: "UI Design, eCommerce Integration",
  //   project: "Static",
  // },
  // {
  //   id: "4",
  //   title: "Restaurant Menu & Booking Website",
  //   description:
  //     "A visually stunning website for a modern restaurant, featuring interactive menus, reservation booking, and customer reviews—all crafted for an immersive dining experience online.",
  //   images: ["/projects/restorent.jpeg"],
  //   liveUrl: "https://qitchendummy.vercel.app",
  //   rating: 5,
  //   tags: ["Full Stack", "Restaurant"],
  //   year: "2024",
  //   client: "Urban Taste",
  //   services: "Web Development, SEO",
  //   project: "Static",
  // },
  // {
  //   id: "5",
  //   title: "Salon Appointment Booking System",
  //   description:
  //     "A sleek and stylish website with integrated appointment booking, service selection, and stylist portfolios. Designed for effortless client interaction and streamlined salon operations.",
  //   images: ["/projects/salon.jpeg"],
  //   liveUrl: "https://salondummy.vercel.app",
  //   rating: 4,
  //   tags: ["UI/UX", "Booking"],
  //   year: "2024",
  //   client: "GlowUp Studio",
  //   services: "Web Design, Booking Integration",
  //   project: "Static",
  // },
  // {
  //   id: "6",
  //   title: "Dental Booking UI",
  //   description:
  //     "Stylish and intuitive frontend for a Dental appointment system.",
  //   images: ["/projects/dental.jpg"],
  //   liveUrl: "https://dainteldummy.vercel.app",
  //   rating: 5,
  //   tags: ["UI/UX", "Booking"],
  //   year: "2024",
  //   client: "GlowUp Studio",
  //   services: "Web Design, Booking Integration",
  //   project: "Static",
  // },
];
